### ISSUE TITLE
Hidden activities / resources are shown in the menu

### ISSUE THREAD

**Issue by matcho** [bmbrands/moodle-block_course_modulenavigation#1]
Hi.

Activities and resources having a visibility set to "hidden" are shown in the menu, although they shouldn't.
Tried with an activity (questionnaire) and a resource (page), both are displayed.

Note that hidden sections are correctly not shown.

Thanks,
Mathias

**Comment by clementpr** [comment]
Hi Matcho,

Thank you for your feedback. I try on my Moodle and I can reproduce this bug.

Best regards.

Clément

**Comment by matcho** [comment]
Hi Clementpr

Just added a pull request.

All the best
Mathias
