### ISSUE TITLE
Make the section links point at section pages

### ISSUE THREAD

**Issue by matcho** [bmbrands/moodle-block_course_modulenavigation#2]
Hi again,

Depending on the course layout, one might find useful to be able to display a section page, instead of going directly to an activity / resource.

An option could make the section titles point at section pages, and move the expand / collapse menu feature to an icon next to the section title for example.

Thanks and congrats for this very useful block !
Mathias

**Comment by clementpr** [comment]
Hi Mathias,

Thank for you feedback about Block course module navigation. In fact, we have something like this only with the option : "display only active section" (see screenshot).
![option-matcho](https://cloud.githubusercontent.com/assets/8448884/15798722/307cffbc-2a43-11e6-848c-cb4a99f6864a.png)

To be sure to understand well your option, can you check this capture ? 
![mathias-request](https://cloud.githubusercontent.com/assets/8448884/15798724/51fc8b9e-2a43-11e6-87c9-ec34c7a45af8.png)

In this mockup, title is a link to section and the arrow expand menu / display section resource.

++

Clément

**Comment by matcho** [comment]
Hi Clément,

Yes this mockup looks like what I had in mind; it would be perfect for my use case.
I might help if needed, depending on the time I'm allowed.

Thanks,
Mathias

**Comment by clementpr** [comment]
Hi Matcho guy,

We reuse your pull request to add a link on section titles. I just modify styles to have the same thing in the 2 modes of the plugin : display all section ((coursenav.mustache) or display only active section (coursenav_onesection.mustache).
I change your image to use one from font awesome too. 
Here is a screenshot : 

<img width="339" alt="capture-modificaiton" src="https://cloud.githubusercontent.com/assets/8448884/17292184/85897666-57e8-11e6-8348-ae959855888e.png">

**Comment by matcho** [comment]
Great, thanks !
Mathias
